sudo: required

language: node_js

node_js:
  - "4"

services:
  - docker

before_install:
  - . ./scripts/env_setup.sh
  - pip install --user awscli

after_success:
  - scripts/docker_push.sh


deploy:
  # deploy dev to the staging environment
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
    on:
      branch: dev
  # deploy master to the production environment
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh
    on:
      branch: master